name: Simple CI/CD for Fake News Detector

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          # Go to application directory
          cd /opt/fake-news-detector || mkdir -p /opt/fake-news-detector && cd /opt/fake-news-detector
          
          # Clone or update repository
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }}.git .
          else
            git pull origin main
          fi
          
          # Stop and restart containers
          docker-compose down || true
          docker-compose up -d --build
          
          # Wait and check status
          sleep 20
          docker-compose ps
          
          echo "✅ Deployment completed!"
          echo "🌐 App URL: http://$(curl -s ifconfig.me || echo 'your-vm-ip')"
